---
# EKS-specific setup tasks
- name: Add cluster autoscaler chart repo
  kubernetes.core.helm_repository:
    name: autoscaler_eks
    repo_url: "https://kubernetes.github.io/autoscaler"

- name: Deploy Cluster Autoscaler (EKS)
  kubernetes.core.helm:
    name: cas
    chart_ref: autoscaler_eks/cluster-autoscaler
    release_namespace: cas
    create_namespace: true
    values:
      autoDiscovery:
        clusterName: cas-eks
      awsRegion: us-east-1
      rbac:
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: "{{ terraform_cluster_result_eks.outputs.cluster_autoscaler_role_arn.value }}"
          create: true
          name: aws-cluster-autoscaler
      extraArgs:
        skip-nodes-with-local-storage: false
        expander: least-waste
        scale-down-enabled: true
        scale-down-delay-after-add: 2m
        scale-down-unneeded-time: 2m
  environment:
    KUBECONFIG: "{{ lookup('vars', 'KUBECONFIG_EKS_CAS') }}" 
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    AWS_DEFAULT_REGION: "us-east-1"

- name: Set Prometheus endpoint facts
  set_fact:
    "PROM_ENDPOINT_EKS_{{ item.cluster | upper }}": "http://127.0.0.1:{{ item.port }}"
  loop:
    - { cluster: 'karpenter', port: 9093 }
    - { cluster: 'cas', port: 9094 }
