apiVersion: karpenter.ibm.sh/v1alpha1
kind: IBMNodeClass
metadata:
  name: auto-placement
spec:
  region: us-south
  vpc: vpc-123
  instanceRequirements:
    architecture: amd64
    minimumCPU: 2
    minimumMemory: 4
    maximumHourlyPrice: 0.5
  placementStrategy:
    zoneBalance: Balanced
    subnetSelection:
      minimumAvailableIPs: 10
