global:
  measurements:
    - name: nodeLatency
    - name: podLatency
    - name: serviceLatency 
      svcTimeout: 5s
  requestTimeout: 60s
  gc: true
  gcMetrics: false
  waitWhenFinished: false  # Changed to false to allow concurrent job execution
  clusterHealth: true

jobs:
  - name: cpu-intensive
    jobIterations: 50
    qps: 40
    burst: 50
    namespacedIterations: true
    namespace: cpu-intensive
    podWait: false        # Changed to false to allow faster pod creation
    cleanup: true
    waitWhenFinished: false
    objects:
      - objectTemplate: files/templates/heterogenous/deployment-cpu-l
        replicas: 20      # Increased from 16
      - objectTemplate: files/templates/heterogenous/deployment-cpu-m
        replicas: 30      # Increased from 8
      - objectTemplate: files/templates/heterogenous/deployment-cpu-s
        replicas: 40      # Increased from 4

  - name: memory-intensive
    jobIterations: 30
    qps: 40
    burst: 50
    namespacedIterations: true
    namespace: memory-intensive
    podWait: false
    cleanup: true
    waitWhenFinished: false
    objects:
      - objectTemplate: files/templates/heterogenous/deployment-memory-m
        replicas: 20
      - objectTemplate: files/templates/heterogenous/deployment-memory-l
        replicas: 30
