global:
  measurements:
    - name: nodeLatency
    - name: podLatency
    - name: serviceLatency 
      svcTimeout: 5s
  requestTimeout: 60s
  gc: true
  gcMetrics: false
  waitWhenFinished: true
  clusterHealth: true

jobs:
  - name: cpu-intensive
    jobIterations: 2400
    qps: 10
    burst: 10
    namespacedIterations: true
    namespace: cpu-intensive
    podWait: false
    cleanup: true
    waitWhenFinished: true
    objects:
      - objectTemplate: files/templates/heterogenous/deployment-cpu-m
        replicas: 28
  - name: memory-intensive
    jobIterations: 2400
    qps: 10
    burst: 10
    namespacedIterations: true
    namespace: memory-intensive
    podWait: false
    cleanup: true
    waitWhenFinished: true
    objects:
      - objectTemplate: files/templates/heterogenous/deployment-memory-m
        replicas: 28
  - name: network-intensive
    jobIterations: 2400
    qps: 10
    burst: 10
    namespacedIterations: true
    namespace: network-intensive
    podWait: false
    cleanup: true
    waitWhenFinished: true
    objects:
      - objectTemplate: files/templates/heterogenous/deployment-network-m
        replicas: 28
  - name: io-intensive
    jobIterations: 2400
    qps: 10
    burst: 10
    namespacedIterations: true
    namespace: io-intensive
    podWait: false
    cleanup: true
    waitWhenFinished: true
    objects:
      - objectTemplate: files/templates/heterogenous/deployment-io-m
        replicas: 28
        