global:
  measurements:
    - name: nodeLatency
    - name: podLatency
    - name: serviceLatency 
      svcTimeout: 5s
  requestTimeout: 60s
  gc: true
  gcMetrics: false
  waitWhenFinished: true
  clusterHealth: true

jobs:
  - name: cpu-intensive
    jobIterations: 10
    qps: 4
    burst: 4
    namespacedIterations: true
    namespace: cpu-intensive
    podWait: false
    cleanup: true
    waitWhenFinished: true
    objects:
      - objectTemplate: files/templates/heterogenous/deployment-cpu-s
        replicas: 4  
      - objectTemplate: files/templates/heterogenous/deployment-cpu-m
        replicas: 4
      - objectTemplate: files/templates/heterogenous/deployment-cpu-l
        replicas: 4
