---
- name: Destroy EKS clusters with Terraform
  community.general.terraform:
    project_path: "{{ playbook_dir }}/../terraform-eks"
    state: absent
    purge_workspace: true
    complex_vars: true
    variables:
      tag_uuid: "{{ tag_uuid }}"
      aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
      flavour: "m5.large"
      kube_version: "1.29"
      worker_count: 1
      worker_pool_count: 3
