---
- name: Destroy EKS clusters with Terraform
  community.general.terraform:
    project_path: "{{ playbook_dir }}/../terraform-eks"
    state: absent
    purge_workspace: true
    complex_vars: true
    variables: "{{ terraform_vars }}"
