---
- hosts: localhost
  connection: local
  vars_files:
    - secrets.yaml
  gather_facts: no
  vars:
    clusters:
      - karpenter
      - cas
    load_test_targets: "{{ lookup('env', 'LOAD_TEST_TARGET') | default('') | split(',') }}"

  tasks:
    - name: Set fact for IBM and AWS tasks based on env
      set_fact:
        run_iks: "{{ 'IBM_CLOUD' in load_test_targets }}"
        run_eks: "{{ 'AWS' in load_test_targets }}"

    - name: Launch IBM Cloud bootstrap task if enabled
      import_tasks: tasks/clusterbootstrap-iks.yaml
      when: run_iks
      tags:
        - setup
        - ibm_cloud
      async: 45
      poll: 0
      register: iks_bootstrap

    - name: Launch AWS bootstrap task if enabled
      import_tasks: tasks/clusterbootstrap-eks.yaml
      when: run_eks
      tags:
        - setup
        - aws
      async: 45
      poll: 0
      register: eks_bootstrap

    - name: Wait for IBM Cloud bootstrap to finish
      async_status:
        jid: "{{ iks_bootstrap.ansible_job_id }}"
        register: job_result_iks
      when: run_iks
      until: job_result_iks.finished
      retries: 100
      delay: 10

    - name: Wait for AWS bootstrap to finish
      async_status:
        jid: "{{ eks_bootstrap.ansible_job_id }}"
        register: job_result_eks
      when: run_eks
      until: job_result_eks.finished
      retries: 100
      delay: 10

    - import_tasks: tasks/clusterconfig.yaml
      ignore_errors: true
      tags:
        - config

    - name: Check if AUTO_RUN_BENCHMARK environment variable is set
      set_fact:
        auto_run_benchmark: "{{ lookup('env', 'AUTO_RUN_BENCHMARK') | default('false') }}"

    - name: Prompt for manual start before benchmarking
      pause:
        prompt: "Press Enter to start benchmarking or Ctrl+C to abort..."
      when: auto_run_benchmark == 'false'

    - name: Include IBM Cloud benchmark tasks if enabled
      include_tasks: tasks/benchmark.yaml
      when: run_iks or run_eks
      tags:
        - benchmark
        - ibm_cloud
        - aws

    - name: Get IBM Cloud billing metrics
      import_tasks: tasks/fetch-billing-ibm.yaml
      when: run_iks
      tags:
        - billing
        - ibm_cloud

    - name: Get AWS Cloud billing metrics
      import_tasks: tasks/fetch-billing-aws.yaml
      when: run_eks
      tags:
        - billing
        - aws

    - name: Check if AUTO_RUN_TEARDOWN environment variable is set
      set_fact:
        auto_run_teardown: "{{ lookup('env', 'AUTO_RUN_TEARDOWN') | default('false') }}"

    - name: Prompt for manual confirmation before teardown
      pause:
        prompt: "Press Enter to start teardown or Ctrl+C to abort..."
      when: auto_run_teardown == 'false'

    - name: Run IBM Cloud teardown if enabled
      include_tasks: tasks/clusterteardown.yaml
      when: run_iks
      tags:
        - teardown
        - ibm_cloud

    - name: Run AWS teardown if enabled
      include_tasks: tasks/clusterteardown.yaml
      when: run_eks
      tags:
        - teardown
        - aws
