---
- hosts: localhost
  connection: local
  vars_files:
    - secrets.yaml
  gather_facts: no
  vars:
    clusters:
      - karpenter
      - cas

  tasks:
    - import_tasks: tasks/clusterbootstrap-iks.yaml
      when: "'IBM_CLOUD' in (lookup('env', 'LOAD_TEST_TARGET') | default(''))"
      tags:
        - setup
        - ibm_cloud

    - import_tasks: tasks/clusterbootstrap-eks.yaml
      when: "'AWS' in (lookup('env', 'LOAD_TEST_TARGET') | default(''))"
      tags:
        - setup
        - aws

    - import_tasks: tasks/clusterconfig.yaml
      ignore_errors: true
      tags:
        - config
    
    - name: Check if AUTO_RUN_BENCHMARK environment variable is set
      set_fact:
        auto_run_benchmark: "{{ lookup('env', 'AUTO_RUN_BENCHMARK') | default('false') }}"

    - name: Prompt for manual start before benchmarking
      pause:
        prompt: "Press Enter to start benchmarking or Ctrl+C to abort..."
      when: auto_run_benchmark == 'false'

    - name: Include IBM Cloud benchmark tasks if enabled
      include_tasks: tasks/benchmark.yaml
      when: "'IBM_CLOUD' in (lookup('env', 'LOAD_TEST_TARGET') | default(''))"
      tags:
        - benchmark
        - ibm_cloud

    - name: Include AWS benchmark tasks if enabled
      include_tasks: tasks/benchmark.yaml
      when: "'AWS' in (lookup('env', 'LOAD_TEST_TARGET') | default(''))"
      tags:
        - benchmark
        - aws

    - name: Check if AUTO_RUN_TEARDOWN environment variable is set
      set_fact:
        auto_run_teardown: "{{ lookup('env', 'AUTO_RUN_TEARDOWN') | default('false') }}"

    - name: Prompt for manual confirmation before teardown
      pause:
        prompt: "Press Enter to start teardown or Ctrl+C to abort..."
      when: auto_run_teardown == 'false'

    - name: Run IBM Cloud teardown if enabled
      include_tasks: tasks/clusterteardown.yaml
      when: "'IBM_CLOUD' in (lookup('env', 'LOAD_TEST_TARGET') | default(''))"
      tags:
        - teardown
        - ibm_cloud

    - name: Run AWS teardown if enabled
      include_tasks: tasks/clusterteardown.yaml
      when: "'AWS' in (lookup('env', 'LOAD_TEST_TARGET') | default(''))"
      tags:
        - teardown
        - aws
