---
- hosts: localhost
  connection: local
  vars_files:
    - secrets.yaml
  gather_facts: no
  vars:
    clusters:
      - karpenter
      - cas
    load_test_targets: "{{ lookup('env', 'LOAD_TEST_TARGET') | default('') | split(',') }}"

  tasks:
    - name: Set fact for IBM and AWS tasks based on env
      set_fact:
        run_iks: "{{ 'IBM_CLOUD' in load_test_targets }}"
        run_eks: "{{ 'AWS' in load_test_targets }}"
      tags:
        - billing
        - setup
        - config 
        - benchmark 
        - teardown

    - name: Debug load_test_targets
      debug:
        var: load_test_targets
      tags:
        - billing
        - setup
        - config 
        - benchmark 
        - teardown

    - name: Generate UUID
      ansible.builtin.command: uuidgen
      register: generated_uuid
      tags:
        - billing
        - setup
        - config
        - benchmark
        - teardown

    - name: Set UUID fact
      ansible.builtin.set_fact:
        tag_uuid: "{{ generated_uuid.stdout }}"
      tags:
        - billing
        - setup
        - config 
        - benchmark 
        - teardown

    - name: Cleanup artefacts from previous runs
      import_tasks: tasks/cleanup.yaml
      when: run_iks
      tags:
        - setup
      vars:
        ansible_become_password: "{{ SUDO_PASSWORD }}"

    - name: Launch IBM Cloud bootstrap task if enabled
      import_tasks: tasks/iks/clusterbootstrap-iks.yaml
      when: run_iks
      tags:
        - setup
      register: iks_bootstrap

    - name: Launch AWS bootstrap task if enabled
      import_tasks: tasks/eks/clusterbootstrap-eks.yaml
      when: run_eks
      tags:
        - setup
      register: eks_bootstrap

    - name: Configure IKS Clusters
      import_tasks: tasks/iks/clusterconfig-iks.yaml
      ignore_errors: true
      when: run_iks
      tags:
        - config

    - name: Configure EKS Clusters
      import_tasks: tasks/eks/clusterconfig-eks.yaml
      ignore_errors: true
      when: run_eks
      tags:
        - config

    - name: IKS benchmark tasks
      include_tasks: tasks/iks/benchmark-iks.yaml
      when: run_iks
      tags:
        - benchmark
      vars:
        ansible_become_password: "{{ SUDO_PASSWORD }}"
        kube_burner_version: 'V1.10.9'   
        kube_burner_arch: 'linux-x86_64'

    - name: EKS benchmark tasks
      include_tasks: tasks/eks/benchmark-eks.yaml
      when: run_eks
      tags:
        - benchmark
      vars:
        ansible_become_password: "{{ SUDO_PASSWORD }}"

    - name: Get IBM Cloud billing metrics
      import_tasks: tasks/iks/fetch-billing-ibm.yaml
      when: run_iks
      tags:
        - billing

    - name: Get AWS Cloud billing metrics
      import_tasks: tasks/eks/fetch-billing-aws.yaml
      when: run_eks
      tags:
        - billing

    - name: Run IBM Cloud teardown if enabled
      include_tasks: tasks/iks/clusterteardown-iks.yaml
      when: run_iks
      tags:
        - teardown

    - name: Run AWS teardown if enabled
      include_tasks: tasks/eks/clusterteardown-eks.yaml
      when: run_eks
      tags:
        - teardown
