apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-intensive-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cpu-intensive
  template:
    metadata:
      labels:
        app: cpu-intensive
    spec:
      containers:
      - name: cpu-intensive-container
        image: ghcr.io/vish/stress:latest
        resources:
          requests:
            cpu: "1000m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "256Mi"
        command: ["stress"]
        args: 
        - "--cpu"
        - "1"
        - "--timeout"
        - "3600"
        - "--vm"
        - "1"
        - "--vm-bytes"
        - "64M"
        - "--vm-stride"  # Added memory stride for varied memory access patterns
        - "128"
        - "--hdd"       # Added disk stress
        - "1"
        - "--hdd-bytes"
        - "128M"
