apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-intensive-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cpu-intensive
  template:
    metadata:
      labels:
        app: cpu-intensive
    spec:
      containers:
      - name: cpu-intensive-container
        image: ghcr.io/vish/stress:latest
        resources:
          requests:
            cpu: "4000m"
            memory: "512Mi"
          limits:
            cpu: "4000m"
            memory: "1Gi"
        command: ["stress"]
        args: 
        - "--cpu"
        - "4"
        - "--timeout"
        - "3600"        # Increased timeout to 1 hour
        - "--vm"        # Added memory stress
        - "2"
        - "--vm-bytes"
        - "256M"
        - "--vm-hang"
        - "1"
