apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-intensive-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cpu-intensive
  template:
    metadata:
      labels:
        app: cpu-intensive
    spec:
      containers:
      - name: cpu-intensive-container
        image: ghcr.io/vish/stress:latest
        resources:
          requests:
            cpu: "2000m"
            memory: "256Mi"
          limits:
            cpu: "2000m"
            memory: "512Mi"
        command: ["stress"]
        args: 
        - "--cpu"
        - "2"
        - "--timeout"
        - "3600"
        - "--vm"
        - "1"
        - "--vm-bytes"
        - "128M"
        - "--io"        # Added IO stress for varied load
        - "2"
